# Golang application builder steps
FROM golang:latest as builder
WORKDIR /go/src/github.com/proepkes/speeddate/usersvc
COPY . .
RUN go get -v ./...
WORKDIR /go/src/github.com/proepkes/speeddate/usersvc/cmd/user
RUN CGO_ENABLED=0 GOOS=linux go build

FROM scratch 
COPY --from=builder /go/src/github.com/proepkes/speeddate/usersvc/keys ./keys
COPY --from=builder /go/src/github.com/proepkes/speeddate/usersvc/gen/http/openapi.json .
COPY --from=builder /go/src/github.com/proepkes/speeddate/usersvc/cmd/user/user . 
ENTRYPOINT ["./user"]
